---
# opencast-bigbluebutton-recordings-plugin configuration file.

# Opencast configuration
opencast:
  # Url of the opencast server.
  # Not trailing slashes allowed.
  url: "https://develop.opencast.org"

  # Username and password to authorize against the opencast server.
  username: "admin"
  password: "opencast"

  # Time after which the cache entries expire.
  cache_expiration: "1m"

  # Time after which a request is considered as failed.
  request_timeout: "10s"

# BigBlueButton configuration
bigbluebutton:
  # BigBlueButton Secret. If empty, security is disabled.
  # For more information, take a look at
  # https://docs.bigbluebutton.org/dev/api.html#api-security-model
  secret:

# Server Configuration
server:
  # Address the server is listen to.
  address: "127.0.0.1:8000"
