name: Test and build Plugin
on: [push, pull_request]
jobs:
  build-and-test:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -v -o opencast-bigbluebutton-recordings-plugin ./...

      - uses: actions/upload-artifact@v2
        with:
          name: opencast-bigbluebutton-recordings-plugin_linux_amd64
          path: ./opencast-bigbluebutton-recordings-plugin
